### ISSUE TITLE
Audapter Manual Not Found

### ISSUE THREAD

**Issue by prlabu** [shanqing-cai/audapter_matlab#5]
When I click on the following link for the manual, I get a 404 Not Found Github page. Is this package still maintained? 
http://scai.io/AudapterManual.pdf

Same for http://scai.io/Audapter/Audapter.mexw64 and http://scai.io/Audapter/Audapter.mexw32

**Comment by caisq** [comment]
Sorry for the inconvenience @prlabu . You can find the pdf and mex* files you're looking for at: 
http://sites.bu.edu/guentherlab/software/audapter/

We'll fix the links later.
