### ISSUE TITLE
Unknown parameter name: btimedomainshift

### ISSUE THREAD

**Issue by prlabu** [shanqing-cai/audapter_matlab#8]
Hi again - sorry to bother you with another issue. I have access to a Windows laptop and am trying to get Audapter set up on it. 

I believe I have the environment set up as expected, with the following structure: 
`/c/speechres/audapter/Audapter-2.1/BIN/Release/Audapter.mexw64`
`/c/speechres/audapter/audapter_matlab` (with corresponding code within)
`/c/speechres/commoncode` (with corresponding code within)

In MATLAB, `which Audapter` successfully returns `/c/speechres/audapter/Audapter-2.1/BIN/Release/Audapter.mexw64`

However, when I try the recommended `test_audapter('formant', '--play')` I get the following error
```
Error using Audapter
Unknown parameter name: btimedomainshift

Error in AudapterIO
Audapter(3, 'btimedomainshift', 0, toPrompt); 

Error in test_audapter
AudapterIO('init', p)
```

Would you have any recommendations to chase this down?

**Comment by prlabu** [comment]
After debugging a bit, it seems like there might be a disparity between the version of audapter_matlab and the MEX file (found at http://sites.bu.edu/guentherlab/files/2016/11/Audapter_MEX-Files.zip) that is distributed. There are a few parameters that the MATLAB API assumes are present (`fb2Gain`, `pitchupperboundhz`, `btimedomainshift`, amongst a few others) which are not handled in Audapter.mex function. Could this be the case? Is it worth trying to compile the C++ from scratch rather than using MEX file you provide?

**Comment by caisq** [comment]
yeah, sorry. @prlabu You're right that there is a version skew between the mex files you downloaded from bu.edu and the MATLAB code on GitHub here. I'll make a TODO item for myself to fix that skew.

**Comment by caisq** [comment]
The download link for the precompiled mexw64 file has been updated in the README file. You can find versioned mexw64 files in https://github.com/shanqing-cai/audapter_mex/tree/master/bin

Version 2.1.5 is current the latest version.
